meta:
  schema-version: 0.1.0
  created-on: "2024-02-04T13:00:15Z"
  cli-version: 0.2.0
projects:
  iamtugy-react-lazylog:
    targets:
      - package.json
    manager:
      ecosystem: node
      name: yarn
      version: "1"
    overrides:
      loader-utils:
        0.2.17:
          use: 0.2.17-sp1
        1.2.3:
          use: 1.2.3-sp1
      async:
        2.6.3:
          use: 2.6.3-sp1
      lodash:
        4.17.15:
          use: 4.17.15-sp1
      semver:
        5.7.1:
          use: 5.7.1-sp1
      ansi-regex:
        3.0.0:
          use: 3.0.0-sp1
      semver-regex:
        1.0.0:
          use: 1.0.0-sp1
      ini:
        1.3.5:
          use: 1.3.5-sp1
      glob-parent:
        3.1.0:
          use: 3.1.0-sp1
      acorn:
        5.7.3:
          use: 5.7.3-sp1
      minimatch:
        3.0.4:
          use: 3.0.4-sp1
      yargs-parser:
        7.0.0:
          use: 7.0.0-sp1
      trim:
        0.0.1:
          use: 0.0.1-sp1
      nth-check:
        1.0.2:
          use: 1.0.2-sp1
      js-yaml:
        3.7.0:
          use: 3.7.0-sp1
      minimist:
        1.2.0:
          use: 1.2.0-sp1
        0.0.8:
          use: 0.0.8-sp1
      lodash.template:
        3.6.2:
          use: 3.6.2-sp1
      json5:
        0.5.1:
          use: 0.5.1-sp1
      decode-uri-component:
        0.2.0:
          use: 0.2.0-sp1
